package.json, src/app/app.module.ts, src/app/core/authentication/authentication.service.ts, src/app/core/init/keycloak-init.factory.ts, src/app/core/shell/sidenav/sidenav.component.ts, src/app/home/home.component.ts, src/app/settings/settings.service.ts, src/app/web-app.component.ts, src/environments/environment.prod.ts, src/environments/environment.ts
https://oneacrefund.atlassian.net/browse/SER-1103
Describe the changes made and why they were made instead of how they were made. List any dependencies that are required for this change.
- [{first-ticket-number} - {first-ticket-description}]({link-to-Jira-ticket})
.
=> KeyCloak integration

src/app/core/authentication/authentication.guard.ts, src/app/core/authentication/authentication.service.ts, src/app/core/shell/sidenav/sidenav.component.ts, src/app/core/shell/toolbar/toolbar.component.ts, src/app/organization/offices/offices.component.html, src/app/organization/offices/offices.component.ts, src/app/shared/office-tree-view/office-tree-node.spec.ts, src/app/shared/office-tree-view/office-tree-node.ts, src/app/shared/office-tree-view/office-tree-view.component.html, src/app/shared/office-tree-view/office-tree-view.component.scss, src/app/shared/office-tree-view/office-tree-view.component.spec.ts, src/app/shared/office-tree-view/office-tree-view.component.ts, src/app/shared/shared.module.ts, src/app/web-app.component.ts, src/assets/env.js, src/environments/environment.prod.ts, src/environments/environment.ts, src/index.html
Describe the changes made and why they were made instead of how they were made. List any dependencies that are required for this change.
- [{first-ticket-number} - {first-ticket-description}]({link-to-Jira-ticket})
.
=> SER-1106 OU Module: Treeview implementation of OUs

src/app/organization/currencies/create-currencies/create-currencies.component.html, src/app/organization/currencies/create-currencies/create-currencies.component.scss, src/app/organization/currencies/create-currencies/create-currencies.component.spec.ts, src/app/organization/currencies/create-currencies/create-currencies.component.ts, src/app/organization/currencies/currencies.component.html, src/app/organization/currencies/currencies.component.ts, src/app/organization/organization-routing.module.ts, src/app/organization/organization.module.ts, src/app/organization/organization.service.ts
UI Changes
New Screens created for Currency
- [{first-ticket-number} - {first-ticket-description}]({link-to-Jira-ticket})
.
=> Sonar Cloud currency configuration

package.json, src/app/app.module.ts, src/app/notifications/notifications.service.ts, src/app/products/loan-product-allocation-setting/loan-product-allocation-setting.component.html, src/app/products/loan-product-allocation-setting/loan-product-allocation-setting.component.scss, src/app/products/loan-product-allocation-setting/loan-product-allocation-setting.component.spec.ts, src/app/products/loan-product-allocation-setting/loan-product-allocation-setting.component.ts, src/app/products/loan-product-allocation-setting/loan-product-allocation.resolver.ts, src/app/products/loan-product-allocation-setting/loan-product-allocation/loan-product-allocation.component.html, src/app/products/loan-product-allocation-setting/loan-product-allocation/loan-product-allocation.component.scss, src/app/products/loan-product-allocation-setting/loan-product-allocation/loan-product-allocation.component.spec.ts, src/app/products/loan-product-allocation-setting/loan-product-allocation/loan-product-allocation.component.ts, src/app/products/loan-product-allocation-setting/loan-product-and-template.resolver.ts, src/app/products/loan-products/loan-product-stepper/loan-product-charges-step/loan-product-charges-step.component.ts, src/app/products/products-routing.module.ts, src/app/products/products.component.html, src/app/products/products.module.ts, src/app/products/products.service.ts, src/app/settings/settings.service.ts, src/app/shared/country-tree-view/country-tree-view.component.ts, src/app/shared/footer/footer.component.ts, src/polyfills.ts
The whole loan allocation protocol involves the list view, the add view as currently implemented and visible in loans.test. Implemented all screens for the loan allocation process.
#{Issue Number}
=> SER-1517 component created for loan allocation products

RELEASE_NOTES.md, src/app/clients/clients-view/client-actions/accept-client-transfer/accept-client-transfer.component.ts, src/app/clients/clients-view/client-actions/reject-client-transfer/reject-client-transfer.component.ts, src/app/clients/clients-view/client-actions/undo-client-transfer/undo-client-transfer.component.ts
Changes to Client transfer api calls
- [SER-1569 - Check how transfer client endpoint works](https://oneacrefund.atlassian.net/browse/SER-1569)
.
=> SER-1569/Fix client transfer api call erros

RELEASE_NOTES.md, src/app/organization/bulk-import/bulk-import.component.html, src/app/organization/bulk-import/view-bulk-import/bulk-imports.ts
=> feat: SER-1538 Implement healthy path upload in Fineract UI v2

RELEASE_NOTES.md, src/app/loans/common-resolvers/loan-action-button.resolver.ts, src/app/loans/loans-view/loan-account-actions/loan-account-actions.component.html, src/app/loans/loans-view/loan-account-actions/top-up-loan/top-up-loan.component.html, src/app/loans/loans-view/loan-account-actions/top-up-loan/top-up-loan.component.scss, src/app/loans/loans-view/loan-account-actions/top-up-loan/top-up-loan.component.spec.ts, src/app/loans/loans-view/loan-account-actions/top-up-loan/top-up-loan.component.ts, src/app/loans/loans-view/loan-accounts-button-config.ts, src/app/loans/loans.module.ts, src/app/loans/loans.service.ts
Added top up implementation
[SER-1536]
(https://oneacrefund.atlassian.net/browse/SER-1536)
[SER-1536]: https://oneacrefund.atlassian.net/browse/SER-1536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add loan topup option

RELEASE_NOTES.md, src/app/core/authentication/authentication.service.ts
Logout redirect update
Can be tested here: http://65.108.247.228:31506
.
=> feat: SER-1895 Fix logout redirect

.github/linters/yamllint.yml, .github/workflows/build.yml, .github/workflows/megalinter.yml, .gitignore, .mega-linter.yml, .vscode/settings.json, azure-pipelines.yml, sonar-project.properties, src/environments/.env.ts
Add the `Build.SonarAnalyse` environment variable to the Azure DevOps build pipeline so that the SonarCloud scan task runs on demand.
=> build: add an env var to Azure DevOps pipeline

RELEASE_NOTES.md, src/app/products/charges/charges.component.html, src/app/products/charges/charges.component.ts, src/app/products/charges/create-charge/create-charge.component.html, src/app/products/charges/create-charge/create-charge.component.ts, src/app/products/charges/view-charge/view-charge.component.html
- Added extension charge options(frequency, interval,extension)
- Update view to include Country and isExtensive column
.
=> feat: SER-1521 Add extension charge

RELEASE_NOTES.md, package-lock.json, package.json, src/app/clients/clients-view/client-actions/transfer-client/transfer-client.component.html, src/app/core/http/http.service.ts, src/app/organization/bulk-import/bulk-repayment-download/bulk-repayment-download.component.html, src/app/organization/bulk-import/view-bulk-import/view-bulk-import.component.html, src/app/organization/currencies/create-currencies/create-currencies.component.html, src/app/organization/offices/combine-office/combine-office.component.html, src/app/organization/offices/combine-office/combine-office.component.scss, src/app/organization/offices/combine-office/combine-office.component.ts, src/app/organization/offices/create-office/create-office.component.html, src/app/organization/offices/edit-office/edit-office.component.html, src/app/organization/offices/offices.component.html, src/app/organization/offices/offices.component.scss, src/app/organization/offices/offices.component.ts, src/app/organization/offices/split-office/split-office.component.html, src/app/organization/offices/split-office/split-office.component.ts, src/app/organization/rural-outlet/create-outlet/create-outlet.component.html, src/app/organization/rural-outlet/create-outlet/create-outlet.component.ts, src/app/products/charges/create-charge/create-charge.component.html, src/app/products/loan-product-allocation-setting/loan-product-allocation/loan-product-allocation.component.html, src/app/products/loan-product-allocation-setting/loan-product-allocation/loan-product-allocation.component.ts, src/app/products/loan-products/loan-product-stepper/loan-product-details-step/loan-product-details-step.component.html, src/app/products/loan-products/loan-product-stepper/loan-product-organization-unit-step/loan-product-organization-unit-step.component.html, src/app/products/loan-products/loan-product-stepper/loan-product-organization-unit-step/loan-product-organization-unit-step.component.ts, src/app/shared/material.module.ts, src/app/system/configurations/global-configurations-tab/clone-configuration/clone-configuration.component.html, src/app/system/configure-data-fields/configure-data-fields.component.html, src/app/system/configure-data-fields/data-fields/data-fields.component.html
Replace mat-select filter with ng select and improve the loading of data in the office view interface.
- SER-2458
.
=> Ser 2458/replace matselect filter

.vscode/settings.json, RELEASE_NOTES.md, src/app/clients/client-stepper/client-general-step/client-general-step.component.html, src/app/clients/client-stepper/client-general-step/client-general-step.component.scss, src/app/clients/clients-view/client-actions/transfer-client/transfer-client.component.html, src/app/clients/clients-view/client-actions/transfer-client/transfer-client.component.scss, src/app/clients/clients-view/clients-view.component.html, src/app/core/shell/sidenav/sidenav.component.html, src/app/core/shell/toolbar/toolbar.component.html, src/app/groups/create-group/create-group.component.html, src/app/groups/create-group/create-group.component.scss, src/app/organization/offices/combine-office/combine-office.component.html, src/app/organization/offices/combine-office/combine-office.component.scss, src/app/organization/offices/create-office/create-office.component.scss, src/app/organization/offices/edit-office/edit-office.component.html, src/app/organization/offices/edit-office/edit-office.component.scss, src/app/organization/offices/split-office/split-office.component.html, src/app/organization/offices/split-office/split-office.component.scss, src/app/users/create-user/create-user.component.scss
Show office hierrachy name instead of office name, show required menus and show client status and substance
- https://oneacrefund.atlassian.net/browse/SER-2510
.
=> Ser 2510/show officehierachy name

RELEASE_NOTES.md, src/app/products/saving-products/saving-product-stepper/saving-product-details-step/saving-product-details-step.component.html, src/app/products/saving-products/saving-product-stepper/saving-product-details-step/saving-product-details-step.component.ts
Ability to select a country and a loan product when creating a savings account.
#https://oneacrefund.atlassian.net/browse/SER-2486
=> feat: SER-2486/Select country-loan product when creating savings account

RELEASE_NOTES.md, src/.prettierrc, src/app/clients/clients.component.html, src/app/clients/clients.component.ts, src/app/groups/groups.component.html, src/app/groups/groups.component.ts, src/app/products/loan-products/loan-products.component.html, src/app/products/loan-products/loan-products.component.ts, src/app/products/loan-products/view-loan-product/view-loan-product.component.html
The displayed columns in the clients and loan products components have been updated to include additional fields. This change improves the visibility of relevant information for users. The 'clients.component.ts' file now displays the 'office' and 'officeHierarchyPath' columns, while the 'loan-products.component.ts' file displays the 'loanType' column. These changes enhance the user experience and provide more comprehensive data in the respective components.
- https://oneacrefund.atlassian.net/browse/SER-1922
- https://oneacrefund.atlassian.net/browse/SER-1912
- https://oneacrefund.atlassian.net/browse/SER-1911
.
=> feat: Update displayed columns in clients and loan products components

RELEASE_NOTES.md, src/app/loans/loans-view/transactions/view-transaction/view-transaction.component.html
[SER-1908] - Include Phone Number in Repayment Transaction Details
[SER-1913] - Exclude the ability to Edit Repayments in Fineract
- https://oneacrefund.atlassian.net/browse/SER-1913
- https://oneacrefund.atlassian.net/browse/SER-1908
.
[SER-1908]: https://oneacrefund.atlassian.net/browse/SER-1908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SER-1913]: https://oneacrefund.atlassian.net/browse/SER-1913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Include Phone Number in Repayment Transaction Details

RELEASE_NOTES.md, src/app/organization/organization.service.ts, src/app/system/configurations/global-configurations-tab/clone-configuration/clone-configuration.component.html, src/app/system/configurations/global-configurations-tab/clone-configuration/clone-configuration.component.ts, src/app/system/configurations/global-configurations-tab/edit-configuration/edit-configuration.component.html, src/app/system/configurations/global-configurations-tab/edit-configuration/edit-configuration.component.ts, src/app/system/configurations/global-configurations-tab/global-configuration.resolver.ts, src/app/system/configurations/global-configurations-tab/global-configurations-tab.component.html, src/app/system/configurations/global-configurations-tab/global-configurations-tab.component.ts
Add support for OU level configuration with code value selection such as `payment-channel`
- Configuration list UI
- Edit Configuration UI
- Clone Configuration UI
=> Add support for OU level config - SER-2523

azure-pipelines.yml
Azure Pipeline: Add conditions to building artifacts
=> Azure Pipeline: Add conditions to building artifacts

azure-pipelines.yml
Disabling validating linting on all the codebase for now as we have a lot of legacy code
=> Disabling validating linting on all the codebase for now as we have a lot of legacy code

.mega-linter.yml, RELEASE_NOTES.md, src/app/organization/bulk-import/bulk-import.component.html, src/app/organization/bulk-import/view-bulk-import/view-bulk-import.component.ts, src/app/system/manage-hooks/add-event-dialog/add-event-dialog.component.ts
[SER-2549] - Implement Loan Account Bulk Upload in Fineract v2
#[SER-2549] - Implement Loan Account Bulk Upload in Fineract v2
[SER-2549]: https://oneacrefund.atlassian.net/browse/SER-2549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SER-2549]: https://oneacrefund.atlassian.net/browse/SER-2549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SER_2549/Implement Loan Account Bulk Upload in Fineract v2

azure-pipelines.yml, values.yaml
Add required steps to deploy v2 on Azure
.
=> Add required steps to deploy v2 on Azure

RELEASE_NOTES.md, src/app/clients/clients-view/client-actions/reactivate-client/reactivate-client.component.html, src/app/clients/clients-view/client-actions/reactivate-client/reactivate-client.component.ts, src/app/clients/common-resolvers/client-actions.resolver.ts, src/app/core/http/api-prefix.interceptor.ts, src/app/organization/offices/create-office/create-office.component.html, src/app/system/manage-hooks/create-hook/create-hook.component.html, src/app/system/manage-hooks/create-hook/create-hook.component.ts, src/app/system/manage-hooks/edit-hook/edit-hook.component.html, src/app/system/manage-hooks/edit-hook/edit-hook.component.ts, src/app/system/manage-hooks/view-hook/view-hook.component.html
Update create, edit, view hooks interface to accommodate Rabbit MQ template .
- https://oneacrefund.atlassian.net/browse/SER-2595
.
=> update hooks interface to accomodate Rabbit MQ template

RELEASE_NOTES.md, src/app/products/loan-products/edit-loan-product/edit-loan-product.component.ts, src/app/products/loan-products/loan-product-stepper/loan-product-preview-step/loan-product-preview-step.component.ts
Fix edit loan product failing due to unsupported fields being submitted
=> fix [SER-2600] - Fix edit loan product failing due to unsupported fields being submitted

src/app/products/loan-products/edit-loan-product/edit-loan-product.component.ts
Remove templateForTermsAndConditions if it's empty
=> Remove templateForTermsAndConditions if it's empty

RELEASE_NOTES.md, src/app/users/create-user/create-user.component.ts, src/environments/environment.prod.ts
Remove staff id from payload when creating users
https://oneacrefund.atlassian.net/browse/SER-2606
.
=> feat: Remove staff id from payload when creating users

src/environments/environment.prod.ts
=> fix fineract api url

RELEASE_NOTES.md, src/app/products/loan-products/create-loan-product/create-loan-product.component.html, src/app/products/loan-products/create-loan-product/create-loan-product.component.ts, src/app/products/loan-products/edit-loan-product/edit-loan-product.component.html, src/app/products/loan-products/edit-loan-product/edit-loan-product.component.ts, src/app/products/loan-products/loan-product-stepper/loan-product-apps/loan-product-apps.component.ts, src/app/products/loan-products/loan-product-stepper/loan-product-organization-unit-step/loan-product-organization-unit-step.component.ts, src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.html, src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.ts, src/app/products/products.service.ts
Fix terms and conditions not being populated correctly on create & edit loan product pages
=> fix SER-2600 Fix terms and conditions not being populated correctly on create & edit loan product pages

RELEASE_NOTES.md, src/app/users/create-user/create-user.component.ts
User creation: Set sendPasswordToEmail to always be false
.
=> fix SER-2600 - User creation: Set sendPasswordToEmail to always be false

RELEASE_NOTES.md, src/app/groups/groups-view/group-actions/manage-group-members/manage-group-members.component.ts
Fix adding member to group due to initialization bug
=> fix SER-2600: Fix adding member to group due to initialization bug

RELEASE_NOTES.md, package.json, src/app/clients/client-stepper/client-general-step/client-general-step.component.html, src/app/clients/edit-client/edit-client.component.html
[SER-2680] - change input type for mobile number field from number to tel to client create and edit interfaces
https://oneacrefund.atlassian.net/browse/SER-2680
[SER-2680]: https://oneacrefund.atlassian.net/browse/SER-2680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: change input type from number to tel

RELEASE_NOTES.md, src/app/core/authentication/authentication.service.ts, src/app/core/shell/sidenav/sidenav.component.ts, src/app/notifications/notifications.service.ts, src/app/organization/offices/create-office/create-office.component.ts, src/app/organization/offices/edit-office/edit-office.component.ts, src/app/shared/office-tree-view/office-tree-view.component.html, src/app/system/manage-hooks/edit-hook/edit-hook.component.ts
[SER-2686] - fix hook routing key editing bug, fix resetting the selected office parent when you select radio button, and fix keycloak error.
https://oneacrefund.atlassian.net/browse/SER-2686
.
[SER-2686]: https://oneacrefund.atlassian.net/browse/SER-2686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ser 2686/fix hook edit

RELEASE_NOTES.md, src/app/groups/groups-view/groups-view.component.html
[SER-2742] - show activate button when a group has been deactivated.
https://oneacrefund.atlassian.net/browse/SER-2742
[SER-2742]: https://oneacrefund.atlassian.net/browse/SER-2742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: show activate button when a group has been deactivated

RELEASE_NOTES.md, src/app/clients/clients-view/clients-view.component.html, src/app/clients/clients-view/custom-dialogs/view-signature-dialog/view-signature-dialog.component.ts
[SER-2763] - fix for view client signature and click group name from client view
https://oneacrefund.atlassian.net/browse/SER-2763
.
[SER-2763]: https://oneacrefund.atlassian.net/browse/SER-2763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: fix view client signature and click group name from client view

RELEASE_NOTES.md, src/app/clients/clients-view/clients-view.component.html, src/app/core/http/error-handler.interceptor.ts, src/app/loans/loans-account-stepper/loans-account-details-step/loans-account-details-step.component.html, src/app/products/loan-products/loan-product-stepper/loan-product-organization-unit-step/loan-product-organization-unit-step.component.ts
[SER-2805] - show proper error message when error status is 400, show client office in the client view,show a searchable dropdown when creating a new client loan.
- https://oneacrefund.atlassian.net/browse/SER-2805
.
[SER-2805]: https://oneacrefund.atlassian.net/browse/SER-2805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: show proper error message when error status is 400

RELEASE_NOTES.md, src/app/groups/groups-view/general-tab/general-tab.component.html, src/app/groups/groups-view/groups-view.component.html
Fix navigations in the group view interface
https://oneacrefund.atlassian.net/browse/SER-2809
=> fix: fix navigations in the group view interface

docker-compose.yml, src/app/organization/sms-campaigns/sms-campaign-stepper/edit-sms-campaign-step/edit-business-rule-parameters/edit-business-rule-parameters.component.ts, src/app/organization/sms-campaigns/sms-campaign-stepper/edit-sms-campaign-step/edit-sms-campaign-step.component.html, src/app/organization/sms-campaigns/sms-campaign-stepper/sms-campaign-step/business-rule-parameters/business-rule-parameters.component.ts, src/app/reports/run-report/run-report.component.ts
Give ability to select All in SMS campaign Office dropdown
=> feat SER-2537 Give ability to select All in SMS campaign Office dropdown

src/app/clients/clients-view/clients-view.component.html, src/app/clients/clients.component.html, src/app/core/shell/toolbar/toolbar.component.html, src/app/loans/loans-view/transactions-tab/transactions-tab.component.html, src/app/loans/loans-view/transactions-tab/transactions-tab.component.ts
Show the admin button on the institution button only if user is a head office user.
.
=> feat: Add conditional rendering for admin menu button

.github/workflows/build.yml
=> feat SER-2803: Add use latest image tag

RELEASE_NOTES.md, src/app/clients/clients.component.html, src/app/system/manage-scheduler-jobs/manage-scheduler-jobs.component.html, src/assets/env.js, src/assets/env.template.js
Search fields on Client Search and Filter Bars are labeled with "Search for Client" and "Filter by Client" respectively and fix null objects in the view jobs interface.
#https://oneacrefund.atlassian.net/browse/SER-2891
=> fix: Update search and filter labels in clients component

RELEASE_NOTES.md, src/app/clients/clients-view/general-tab/general-tab.component.html, src/app/loans/loans-view/loan-accounts-button-config.ts, src/app/loans/loans-view/loans-view.component.ts
Remove loan payment button from the UI
- https://oneacrefund.atlassian.net/browse/SER-2926
.
=> Remove loan payment button from the UI

RELEASE_NOTES.md, package.json
Update the project version to 1.3.0
=> Update the project version to 1.3.0

RELEASE_NOTES.md, src/app/clients/clients-view/client-actions/activate-client/activate-client.component.html, src/app/clients/clients-view/client-actions/activate-client/activate-client.component.ts, src/app/clients/clients-view/client-actions/reactivate-client/reactivate-client.component.html, src/app/clients/clients-view/client-actions/reactivate-client/reactivate-client.component.ts, src/app/clients/clients-view/general-tab/general-tab.component.html, src/app/clients/clients.component.html, src/app/loans/loans-view/loan-accounts-button-config.ts, src/app/loans/loans-view/loans-view.component.ts, src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.html, src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.ts, src/app/system/manage-scheduler-jobs/manage-scheduler-jobs.component.html, src/assets/env.js, src/assets/env.template.js
=> Merge develop into main

RELEASE_NOTES.md, src/app/clients/clients-view/clients-view.component.html, src/app/organization/organization.component.html, src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.html
Show or hide some menus based on user permissions
- https://oneacrefund.atlassian.net/browse/SER-2947
.
=> feat: Show or hide some menus based on user permissions

.github/workflows/build.yml, RELEASE_NOTES.md, package.json
Update Project version & clean up the release notes
=> chore: Prepare Release of 1.3.2

RELEASE_NOTES.md, package.json, src/app/clients/clients-view/clients-view.component.html
Show client's date of birth on profile if present
- https://oneacrefund.atlassian.net/browse/SER-2961
.
=> feat: Add client's date of birth to client profile view

RELEASE_NOTES.md, package.json, src/app/loans/loans.service.ts
Updated to only display client eligible loan product
=> feat: SER-2664 show only client eligible lp

RELEASE_NOTES.md, src/app/organization/organization.service.ts, src/app/products/loan-product-allocation-setting/loan-product-allocation/loan-product-allocation.component.ts, src/app/products/loan-products/loan-product-stepper/loan-product-organization-unit-step/loan-product-organization-unit-step.component.ts, src/app/products/loan-products/loan-product-stepper/loan-product-preview-step/loan-product-preview-step.component.ts, src/app/products/loan-products/view-loan-product/view-loan-product.component.ts
Ability to load OUs up to configured OU level if configured
- [SER-3008](https://oneacrefund.atlassian.net/browse/SER-3008)
.
[SER-3008]: https://oneacrefund.atlassian.net/browse/SER-3008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SER-3008 load OUs up to configured OU level if configured

.github/actions/dispatch/action.yml, .github/workflows/build.yml, README.md, RELEASE_NOTES.md
Add configs for automatically triggering deployment with Github Release
=> chore(SER-2803): Add configs for automatically triggering deployment

.github/workflows/build.yml
Add checkout step in deploy job
.
=> chore(SER-2803): Add checkout step in deploy job

.github/workflows/build.yml
This PR seeks to update the automated trigger step that uses an organization-wide action and provides more inputs for deployment
=> Update the automated deployment step

.github/actions/helm_fineract_frontend/action.yml, .github/workflows/build.yml
Describe the changes made and why they were made instead of how they were made. List any dependencies that are required for this change.
- [{first-ticket-number} - {first-ticket-description}]({link-to-Jira-ticket})
.
=> feat: Add GitHub Actions for  deploying Fineract frontend

RELEASE_NOTES.md, src/app/core/core.module.ts, src/app/core/user-agent/user-agent.interceptor.ts, src/app/core/user-agent/user-agent.service.spec.ts, src/app/core/user-agent/user-agent.service.ts, src/assets/env.js, src/environments/environment.local.ts, src/environments/environment.prod.ts, src/environments/environment.qa.ts, src/environments/environment.test.ts, src/environments/environment.ts
- Introduce the user agent for Mifos. The header name preferred is "X-User-Agent" 
[Ticket](https://oneacrefund.atlassian.net/browse/SER-2543)
=> SER-2543 (Umuganda) - Implement the User Agent

RELEASE_NOTES.md, src/app/clients/edit-client/edit-client.component.ts
Use `country-client-phone-number-otp-expiry-period` to check if OTP validation should be carried out when editing client
=> Update the config name used to check if OTP validation should be initiated - SER-3214

.github/workflows/megalinter.yml, RELEASE_NOTES.md, docker-compose.yml, src/app/clients/clients.component.ts, src/app/clients/clients.datasource.ts, src/app/organization/organization.service.ts, src/app/products/saving-products/saving-product-stepper/saving-product-details-step/saving-product-details-step.component.ts, src/app/settings/settings.service.ts, src/assets/env.js, src/assets/env.template.js, src/environments/environment.local.ts, src/environments/environment.prod.ts, src/environments/environment.qa.ts, src/environments/environment.test.ts, src/environments/environment.ts
- Filter sms campaigns list by country
- Add env var for Keycloak Token URL
- [SER-3088](https://oneacrefund.atlassian.net/browse/SER-3088)
.
[SER-3088]: https://oneacrefund.atlassian.net/browse/SER-3088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix/SER-3088 : Filter sms campaigns list by country & Add env var for Keycloak Token URL

.github/workflows/build.yml
Add dependency on deployment step
=> chore: Add dependency on deployment step

src/app/products/loan-products/loan-product-stepper/loan-product-client-eligibility-step/loan-product-client-eligibility-step.component.ts
This ensures that "0" as a value will be accepted.
Related to https://github.com/one-acre-fund/fineract-frontend-v2/pull/218
=> HOTFIX - Check explicitly for null and undefined client eligibility values

package.json
Change Project version to trigger deployment on UAT
=> chore: Change Project version to trigger deployment on UAT

.github/workflows/build.yml, .github/workflows/deploy.yml
Introduce reusable workflow for deployment to avoid replicate GA env variables
=> chore(SER-3309): Refactor GA deployment jobs to avoid duplicationg env variables
